site_name: OhMyDebn
site_url: https://dougburks.github.io/ohmydebn-docs/
repo_url: https://github.com/dougburks/ohmydebn

plugins:
  - glightbox
  - search

theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
  palette:
    scheme: slate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

nav:
  - Introduction: index.md
  - Motivation: motivation.md
  - Gallery: gallery.md
  - Ingredients: ingredients.md
  - FAQ: faq.md
  - Requirements: requirements.md
  - Warnings: warnings.md
  - Source Code: source-code.md
  - Installation: installation.md
  - Window Tiling: window-tiling.md
  - Desktop Themes: desktop-themes.md
  - Desktop Effects: desktop-effects.md
  - Screen Magnifier: screen-magnifier.md
  - Hotkeys: hotkeys.md
  - OhMyDebn Menu: ohmydebn-menu.md
  - Apps Menu: apps-menu.md
  - Browser: browser.md
  - Text Editor: text-editor.md
  - Documents: documents.md
  - Terminal: terminal.md
  - Utilities: utilities.md
  - Firewall: firewall.md
  - Virtualization: virtualization.md
  - Updating: updating.md
  - Resetting: resetting.md
  - Acknowledgements: acknowledgements.md
